import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { admin } from "better-auth/plugins";
import { nextCookies, toNextJsHandler } from "better-auth/next-js";
import { headers } from "next/headers";
import { db } from "@/db";
import { users, sessions, accounts, verifications } from "@/db/schema/auth";
import { ac, roles } from "@/lib/permissions";
import { eq } from "drizzle-orm";
import { sendEmail } from "@/lib/email";

// Escape user-controlled values before interpolating into email HTML.
const escapeHtml = (s: string) =>
  s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    schema: {
      user: users,
      session: sessions,
      account: accounts,
      verification: verifications,
    },
  }),
  // IDs are uuids generated by Postgres (defaultRandom), not by Better Auth.
  advanced: {
    database: {
      generateId: false,
    },
  },
  // Each Vercel deployment is served on its own host that won't match
  // BETTER_AUTH_URL. Trust only this project's exact hosts (the current
  // deployment + the stable production host, both injected by Vercel) plus the
  // configured base URL (custom domain) — never the whole *.vercel.app tenant.
  trustedOrigins: [
    process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : null,
    process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : null,
    process.env.BETTER_AUTH_URL ?? null,
  ].filter((o): o is string => Boolean(o)),
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    // Sign-ups are staff-provisioning only (no public self-signup UI).
    // autoSignIn would replace the provisioning manager's session with
    // the newly created technician's session.
    autoSignIn: false,
    sendResetPassword: async ({ user, url }) => {
      await sendEmail({
        to: user.email,
        subject: "Reset Your Password — Afridrop Solutions",
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #2563eb;">
              <h1 style="color: #2563eb; margin: 0;">Afridrop Solutions</h1>
            </div>
            <div style="padding: 30px 0;">
              <h2 style="color: #1f2937;">Reset Your Password</h2>
              <p style="color: #4b5563; line-height: 1.6;">Hi ${escapeHtml(user.name)},</p>
              <p style="color: #4b5563; line-height: 1.6;">We received a request to reset your password. Click the button below to create a new one.</p>
              <div style="text-align: center; padding: 20px 0;">
                <a href="${escapeHtml(url)}" style="background-color: #2563eb; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; font-weight: bold;">Reset Password</a>
              </div>
              <p style="color: #9ca3af; font-size: 13px;">If you did not request this, you can safely ignore this email.</p>
            </div>
            <div style="border-top: 1px solid #e5e7eb; padding: 15px 0; text-align: center; color: #9ca3af; font-size: 12px;">
              <p>Afridrop Solutions | afridropsolutions.com</p>
            </div>
          </div>
        `,
      });
    },
  },
  emailVerification: {
    sendVerificationEmail: async ({ user, url }) => {
      await sendEmail({
        to: user.email,
        subject: "Verify Your Email — Afridrop Solutions",
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="text-align: center; padding: 20px 0; border-bottom: 2px solid #2563eb;">
              <h1 style="color: #2563eb; margin: 0;">Afridrop Solutions</h1>
            </div>
            <div style="padding: 30px 0;">
              <h2 style="color: #1f2937;">Verify Your Email</h2>
              <p style="color: #4b5563; line-height: 1.6;">Hi ${escapeHtml(user.name)},</p>
              <p style="color: #4b5563; line-height: 1.6;">Please verify your email address by clicking the button below.</p>
              <div style="text-align: center; padding: 20px 0;">
                <a href="${escapeHtml(url)}" style="background-color: #2563eb; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; font-weight: bold;">Verify Email</a>
              </div>
              <p style="color: #9ca3af; font-size: 13px;">If you did not create an account, you can safely ignore this email.</p>
            </div>
            <div style="border-top: 1px solid #e5e7eb; padding: 15px 0; text-align: center; color: #9ca3af; font-size: 12px;">
              <p>Afridrop Solutions | afridropsolutions.com</p>
            </div>
          </div>
        `,
      });
    },
    sendOnSignUp: true,
  },
  user: {
    additionalFields: {
      firstName: { type: "string", required: true, input: true },
      lastName: { type: "string", required: true, input: true },
      phone: { type: "string", required: false, input: true },
      isActive: { type: "boolean", required: false, input: false, defaultValue: true },
    },
  },
  plugins: [
    admin({
      ac,
      roles,
      defaultRole: "customer",
      adminRoles: ["super_admin"],
    }),
    // nextCookies must be the last plugin.
    nextCookies(),
  ],
});

export const { GET, POST } = toNextJsHandler(auth);

export type Session = typeof auth.$Infer.Session;

// Resolve the current session from request headers (server components/actions).
// Returns null if the session is missing or the user has been deactivated / soft-deleted.
export async function getSession() {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user?.id) return session;

  const [row] = await db
    .select({ isActive: users.isActive, deletedAt: users.deletedAt })
    .from(users)
    .where(eq(users.id, session.user.id))
    .limit(1);

  if (!row || row.isActive === false || row.deletedAt !== null) return null;

  return session;
}

const PRIVILEGED_ROLES = ["super_admin"];

// Returns the session only if the user holds an allowed role, else null.
// Use in form actions (useActionState) that return { error } on rejection.
export async function hasRole(allowed: string[] = PRIVILEGED_ROLES) {
  const session = await getSession();
  if (!session?.user || !allowed.includes((session.user as { role?: string }).role ?? "")) {
    return null;
  }
  return session;
}

// Throws on rejection. Use in plain server actions that don't surface form state.
export async function requireRole(allowed: string[] = PRIVILEGED_ROLES) {
  const session = await hasRole(allowed);
  if (!session) throw new Error("Unauthorized");
  return session;
}
