import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { admin } from "better-auth/plugins";
import { nextCookies, toNextJsHandler } from "better-auth/next-js";
import { headers } from "next/headers";
import { db } from "@/db";
import { users, sessions, accounts, verifications } from "@/db/schema/auth";
import { ac, roles } from "@/lib/permissions";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    schema: {
      user: users,
      session: sessions,
      account: accounts,
      verification: verifications,
    },
  }),
  // IDs are uuids generated by Postgres (defaultRandom), not by Better Auth.
  advanced: {
    database: {
      generateId: false,
    },
  },
  // Vercel serves each deployment on its own *.vercel.app host, which won't
  // match BETTER_AUTH_URL. Trust all Vercel hosts plus any configured base URL
  // (custom domain) so the origin check passes on preview and production.
  trustedOrigins: [
    "https://*.vercel.app",
    ...(process.env.BETTER_AUTH_URL ? [process.env.BETTER_AUTH_URL] : []),
  ],
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
  },
  user: {
    additionalFields: {
      firstName: { type: "string", required: true, input: true },
      lastName: { type: "string", required: true, input: true },
      phone: { type: "string", required: false, input: true },
      isActive: { type: "boolean", required: false, input: false, defaultValue: true },
    },
  },
  plugins: [
    admin({
      ac,
      roles,
      defaultRole: "customer",
      adminRoles: ["admin", "super_admin"],
    }),
    // nextCookies must be the last plugin.
    nextCookies(),
  ],
});

export const { GET, POST } = toNextJsHandler(auth);

export type Session = typeof auth.$Infer.Session;

// Resolve the current session from request headers (server components/actions).
export async function getSession() {
  return auth.api.getSession({ headers: await headers() });
}

const PRIVILEGED_ROLES = ["admin", "super_admin"];

// Returns the session only if the user holds an allowed role, else null.
// Use in form actions (useActionState) that return { error } on rejection.
export async function hasRole(allowed: string[] = PRIVILEGED_ROLES) {
  const session = await getSession();
  if (!session?.user || !allowed.includes((session.user as { role?: string }).role ?? "")) {
    return null;
  }
  return session;
}

// Throws on rejection. Use in plain server actions that don't surface form state.
export async function requireRole(allowed: string[] = PRIVILEGED_ROLES) {
  const session = await hasRole(allowed);
  if (!session) throw new Error("Unauthorized");
  return session;
}
