import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { admin } from "better-auth/plugins";
import { nextCookies, toNextJsHandler } from "better-auth/next-js";
import { headers } from "next/headers";
import { db } from "@/db";
import { users, sessions, accounts, verifications } from "@/db/schema/auth";
import { ac, roles } from "@/lib/permissions";
import { eq } from "drizzle-orm";

export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    schema: {
      user: users,
      session: sessions,
      account: accounts,
      verification: verifications,
    },
  }),
  // IDs are uuids generated by Postgres (defaultRandom), not by Better Auth.
  advanced: {
    database: {
      generateId: false,
    },
  },
  // Each Vercel deployment is served on its own host that won't match
  // BETTER_AUTH_URL. Trust only this project's exact hosts (the current
  // deployment + the stable production host, both injected by Vercel) plus the
  // configured base URL (custom domain) — never the whole *.vercel.app tenant.
  trustedOrigins: [
    process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : null,
    process.env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}` : null,
    process.env.BETTER_AUTH_URL ?? null,
  ].filter((o): o is string => Boolean(o)),
  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
  },
  user: {
    additionalFields: {
      firstName: { type: "string", required: true, input: true },
      lastName: { type: "string", required: true, input: true },
      phone: { type: "string", required: false, input: true },
      isActive: { type: "boolean", required: false, input: false, defaultValue: true },
    },
  },
  plugins: [
    admin({
      ac,
      roles,
      defaultRole: "customer",
      adminRoles: ["super_admin"],
    }),
    // nextCookies must be the last plugin.
    nextCookies(),
  ],
});

export const { GET, POST } = toNextJsHandler(auth);

export type Session = typeof auth.$Infer.Session;

// Resolve the current session from request headers (server components/actions).
// Returns null if the session is missing or the user has been deactivated / soft-deleted.
export async function getSession() {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user?.id) return session;

  const [row] = await db
    .select({ isActive: users.isActive, deletedAt: users.deletedAt })
    .from(users)
    .where(eq(users.id, session.user.id))
    .limit(1);

  if (!row || row.isActive === false || row.deletedAt !== null) return null;

  return session;
}

const PRIVILEGED_ROLES = ["super_admin"];

// Returns the session only if the user holds an allowed role, else null.
// Use in form actions (useActionState) that return { error } on rejection.
export async function hasRole(allowed: string[] = PRIVILEGED_ROLES) {
  const session = await getSession();
  if (!session?.user || !allowed.includes((session.user as { role?: string }).role ?? "")) {
    return null;
  }
  return session;
}

// Throws on rejection. Use in plain server actions that don't surface form state.
export async function requireRole(allowed: string[] = PRIVILEGED_ROLES) {
  const session = await hasRole(allowed);
  if (!session) throw new Error("Unauthorized");
  return session;
}
