name: Build-Test-Deploy

on:
  push:
    branches: [develop, main]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 🆕  install PHP and Composer
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'      # pick the version your site needs
          tools: composer

      - name: Install PHP deps
        run: composer install --no-dev --quiet

      - name: PHPUnit
        run: ./vendor/bin/phpunit --colors=always

  deploy:
    if: github.ref == 'refs/heads/main' && success()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Hostinger auto-deploy
        env:
          WEBHOOK: ${{ secrets.HOSTINGER_WEBHOOK }}
        run: curl -X POST "$WEBHOOK"

